environmentName: dev # Default environment

image:
  repository: utsavnetops/flask-k8s-ops

environments:
  dev:
    replicaCount: 1
    image:
      tag: develop-v0.0.20-dev-dd0fda35476a3a42d025fa5190de657766baac21
    namespace: poddetails-dev
    ingress:
      host: dev.example.com
    service:
      port: 80
      nodePort: 30003

  staging:
    replicaCount: 1
    image:
      tag: release-v0.0.6-staging-05656286c56fbf16d227d3819bd2072ad197b469
    namespace: poddetails-staging
    ingress:
      host: staging.example.com
    service:
      port: 80
      nodePort: 30002

  prod:
    replicaCount: 2
    image:
      tag: v0.0.4-197056c46373b2d4bda6b92aa397a0389fb1457b
    namespace: poddetails-prod
    ingress:
      host: prod.example.com
    service:
      port: 80
      nodePort: 30001
