environmentName: dev # Default environment

image:
  repository: utsavnetops/flask-k8s-ops

environments:
  dev:
    replicaCount: 1
    image:
      tag: develop-v0.0.17-dev-6e3287fdb839fff14f7549b7b5a58027da390661
    namespace: poddetails-dev
    ingress:
      host: dev.example.com
    service:
      port: 80
      nodePort: 30003

  staging:
    replicaCount: 1
    image:
      tag: staging
    namespace: poddetails-staging
    ingress:
      host: staging.example.com
    service:
      port: 80
      nodePort: 30002

  prod:
    replicaCount: 2
    image:
      tag: v0.0.1-prod
    namespace: poddetails-prod
    ingress:
      host: prod.example.com
    service:
      port: 80
      nodePort: 30001
