environmentName: dev # Default environment

image:
  repository: utsavnetops/flask-k8s-ops

environments:
  dev:
    replicaCount: 1
    image:
      tag: v0.0.16-dev
    mongodb:
      host: "{{ .Values.secret.mongodb.host }}"
      port: "{{ .Values.secret.mongodb.port }}"
      username: "{{ .Values.secret.mongodb.username }}"
      password: "{{ .Values.secret.mongodb.password }}"
    namespace: poddetails-dev
    ingress:
      host: dev.example.com
    service:
      port: 80
      nodePort: 30003

  staging:
    replicaCount: 1
    image:
      tag: v0.0.2-staging
    mongodb:
      host: "{{ .Values.secret.mongodb.host }}"
      port: "{{ .Values.secret.mongodb.port }}"
      username: "{{ .Values.secret.mongodb.username }}"
      password: "{{ .Values.secret.mongodb.password }}"
    namespace: poddetails-staging
    ingress:
      host: staging.example.com
    service:
      port: 80
      nodePort: 30002

  prod:
    replicaCount: 2
    image:
      tag: v0.0.1-prod
    mongodb:
      host: "{{ .Values.secret.mongodb.host }}"
      port: "{{ .Values.secret.mongodb.port }}"
      username: "{{ .Values.secret.mongodb.username }}"
      password: "{{ .Values.secret.mongodb.password }}"
    namespace: poddetails-prod
    ingress:
      host: prod.example.com
    service:
      port: 80
      nodePort: 30001

secret:
  mongodb:
    host: ""
    port: ""
    username: ""
    password: ""
