environmentName: dev # Default environment

image:
  repository: utsavnetops/flask-k8s-ops

environments:
  dev:
    replicaCount: 1
    image:
      tag: develop-v0.0.18-dev-550461c11f483929829885e21f028d9536b88d76
    namespace: poddetails-dev
    ingress:
      host: dev.example.com
    service:
      port: 80
      nodePort: 30003

  staging:
    replicaCount: 1
    image:
      tag: release-v0.0.5-staging-0ef308c5c5ce1fa40c5ae755fa1e0ee6367a53bc
    namespace: poddetails-staging
    ingress:
      host: staging.example.com
    service:
      port: 80
      nodePort: 30002

  prod:
    replicaCount: 2
    image:
      tag: v0.0.2-4edc36b0baeebc62a7de9a7f125808a42f663d24
    namespace: poddetails-prod
    ingress:
      host: prod.example.com
    service:
      port: 80
      nodePort: 30001
