environmentName: dev # Default environment

image:
  repository: utsavnetops/flask-k8s-ops

environments:
  dev:
    replicaCount: 1
    image:
      tag: develop-v0.0.19-dev-fc93ad97c66aa00d4c38d77dfc5097a7aaa7c263
    namespace: poddetails-dev
    ingress:
      host: dev.example.com
    service:
      port: 80
      nodePort: 30003

  staging:
    replicaCount: 1
    image:
      tag: release-v0.0.6-staging-05656286c56fbf16d227d3819bd2072ad197b469
    namespace: poddetails-staging
    ingress:
      host: staging.example.com
    service:
      port: 80
      nodePort: 30002

  prod:
    replicaCount: 2
    image:
      tag: v0.0.3-e13657e6e72d100d00397632a29ad039b14f5a01
    namespace: poddetails-prod
    ingress:
      host: prod.example.com
    service:
      port: 80
      nodePort: 30001
