environmentName: dev # Default environment

image:
  repository: utsavnetops/flask-k8s-ops

environments:
  dev:
    replicaCount: 1
    image:
      tag: develop-v0.0.19-dev-683bb59194da6e804a232d23ca8d8c2f6c26985e
    namespace: poddetails-dev
    ingress:
      host: dev.example.com
    service:
      port: 80
      nodePort: 30003

  staging:
    replicaCount: 1
    image:
      tag: release-v0.0.5-staging-c09005247d6855190ee7b69c024106609b0b2e24
    namespace: poddetails-staging
    ingress:
      host: staging.example.com
    service:
      port: 80
      nodePort: 30002

  prod:
    replicaCount: 2
    image:
      tag: v0.0.3-e13657e6e72d100d00397632a29ad039b14f5a01
    namespace: poddetails-prod
    ingress:
      host: prod.example.com
    service:
      port: 80
      nodePort: 30001
