environmentName: dev # Default environment

image:
  repository: utsavnetops/flask-k8s-ops

environments:
  dev:
    replicaCount: 1
    image:
      tag: develop-v0.0.20-dev-3fbe97cc903bee23994d93954ae5d247eb167531
    namespace: poddetails-dev
    ingress:
      host: dev.utsavops.com
    service:
      port: 80
      nodePort: 30003

  staging:
    replicaCount: 1
    image:
      tag: release-v0.0.7-staging-24b3ec614e8becae36b428049aadfc6418bbeace
    namespace: poddetails-staging
    ingress:
      host: staging.utsavops.com
    service:
      port: 80
      nodePort: 30002

  prod:
    replicaCount: 2
    image:
      tag: v0.0.4-197056c46373b2d4bda6b92aa397a0389fb1457b
    namespace: poddetails-prod
    ingress:
      host: prod.utsavops.com
    service:
      port: 80
      nodePort: 30001
