apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-k8s-service
  namespace: {{ index .Values.environments .Values.environmentName "namespace" }}
spec:
  type: NodePort
  selector:
    app: flask-k8s-app
  ports:
  - protocol: TCP
    port: {{ index .Values.environments .Values.environmentName "service" "port" }}
    targetPort: 5000
    nodePort: {{ index .Values.environments .Values.environmentName "service" "nodePort" }}
